### ISSUE TITLE
UX: If Main window is not Maximized, exiting FreeCAD and restarting, the Main window will not restore to the prior position

### ISSUE THREAD

**Issue by Buffalo1John** [FreeCAD/FreeCAD#14649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you start FreeCAD, Restore Down the main Window, move it on the screen , then exit the program, upon restart the main window will not return to the position it was in when exiting occured.

It works correctly on 0.21.2

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git)
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.64a
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28
```

### Subproject(s) affected?

None

### Anything else?

![BeforeExitWindowsOrientation](https://github.com/FreeCAD/FreeCAD/assets/46139884/a43c6161-0c43-43d5-82c9-781e0c6b9822)
![AfterRestartWindowsShift](https://github.com/FreeCAD/FreeCAD/assets/46139884/a117fc1a-01b3-406d-8f39-4ec1f030b9e5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
It should've been fixed with https://github.com/FreeCAD/FreeCAD/pull/11275#issuecomment-1805231598
@wwmayer FYI

**Comment by Buffalo1John** [comment]
I just tried it on 0.21.2:
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.64a
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28
[/code]

closed this:
![0 21 2A](https://github.com/FreeCAD/FreeCAD/assets/46139884/ed53cc79-1417-49c2-b658-72317984dc7a)

when opened saw this:
![0 21 2B](https://github.com/FreeCAD/FreeCAD/assets/46139884/758558c7-ad8a-40c7-a839-a0c08bcb9493)

**Comment by Buffalo1John** [comment]
Here it is with 0.22dev:
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37709 (Git)
Build type: Release
Branch: main
Hash: dd816a635ccacc39f29b1761c6ccfed21a90b646
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.64a
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28

closed this:
![0 22A](https://github.com/FreeCAD/FreeCAD/assets/46139884/196ed231-6ee2-4455-807e-79bbf6905c8c)

then opened to see this:
![0 22B](https://github.com/FreeCAD/FreeCAD/assets/46139884/fddb220f-a60e-4226-a705-812bbabcd575)

**Comment by maxwxyz** [comment]
is it still an issue in the latest weekly?

**Comment by Buffalo1John** [comment]
Yes, this is still an issue...

OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.65
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28

**Comment by Buffalo1John** [comment]
Still found on 0.22.0dev.38419

OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.65
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28

**Comment by luzpaz** [comment]
Related: #17221

**Comment by Buffalo1John** [comment]
This remains a bug in weekly build 42461 which I just downloaded and tested.

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42461 (Git)
Build date: 2025/06/30 16:12:02
Build type: Release
Branch: main
Hash: 60aa5ff3730d77037ffad0c77ba96b99ef0c7df3
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * A2plus 0.4.68
  * Curves 0.6.61
  * fasteners 0.5.38
  * lattice2 1.0.0

**Comment by Buffalo1John** [comment]
Yes, this is still a bug. 

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/02 21:58:19
Build type: Release
Branch: main
Hash: 04e085cba3b43d1e09aedd4445824a6eb46e45b6
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * A2plus 0.4.68
  * Curves 0.6.61
  * fasteners 0.5.38
  * lattice2 1.0.0

It behaves the same way it did when it was first reported.

**Comment by luzpaz** [comment]
Wild this still happens on Qt6 for you. Odd.

**Comment by maxwxyz** [comment]
Same happens for me on Win11

**Comment by ipatch** [comment]
is this just something specific to windows 11 or does it affect all OSes ie. gnu+linux and macos as well?

**Comment by Buffalo1John** [comment]
I run Windows 10

**Comment by ipatch** [comment]
i think this might be something specific to windows. i just tested this behavior with both v1.0.2 and the latest dev build on asahi linux, and am unable to reproduce.

steps i performed.

1. launch freecad (it was starting maximized in my case)
2. unmaximized the main window
3. shrink the windo to arbitrary size on the screen.
4. dragged the report panel out of the main window (so that it's floating independently of the main window)
5. quit freecad
6. relaunch freecad.

both the main window and the report window opened at the same location as they were when i closed / quit freecad.

**Comment by Buffalo1John** [comment]
Are you doing multiple screens? I have three.

I dragged the main window across the screen boundary. Why? To try to get the tiled windows to be across the boundary to leave more room on the main view of the thing being worked on. Sure it is unconventional, but there is another bug that the task panel walks itself off the screen. If that one would get fixed, I wouldn't care about this one, but I found it trying to work around the much more annoying **Overlay: When Undocked, widgets in the Tasks panel will shift down and right (Windows)** #14650

I only have windows, so I can't test linux or mac. It fails with QT5 (original PR) and QT6 (current 1.1.0dev).

**Comment by ipatch** [comment]
unfortunately i use rdp (via X11vnc (don't ask 😑)) to login to this m1 mac running asahi (it doesn't have a monitor connected to it). so the dekstop is just one screen / main window. so i can not test across multiple monitors / screen boundaries that i know of.

**Comment by luzpaz** [comment]
@Syres916 i think I saw you comment on a similar ticket recently regarding screen coordinates... or am I totally wrong ?

**Comment by herrdeh** [comment]
I have a very similar problem on 

OS: Ubuntu 24.04.3 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0rc1.20251125 (Git shallow) AppImage
Build date: 2025/11/25 17:53:08
Build type: Release
Branch: (HEAD detached at 5376760)
Hash: 53767601ea65de7cd9f6590e7d5856afc0841635

and had that ever since:

* I use standard view with an open spreadsheet,
*  maybe arrange those two windows in a special manner
* hit Shift-F to save this view 
* save the file
* reopen it
-> main window / spreadsheet arrangement is lost
-> open spreadsheet is lost anyway

Described in #17221.
