### ISSUE TITLE
PD Mirror: project created with v0.21 can't be edited with v0.22

### ISSUE THREAD

**Issue by Panda631** [FreeCAD/FreeCAD#15881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Find attached a file created with v0.21. Everything is OK.

If you open it in v0.22, the body is visible, but a number of error messages are displayed.

![grafik](https://github.com/user-attachments/assets/97d6c92d-c09e-45b9-8911-55b61dacdca0)

The check geometry result doesn't show any problem.

![grafik](https://github.com/user-attachments/assets/2f284bc0-5517-4d6f-8e63-273a1f6fe113)

After recompute, the body is destroyed.

![grafik](https://github.com/user-attachments/assets/6e100b16-7d7f-49a5-8942-640e61f37d4d)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * EM 2.1.1
  * fasteners 0.5.21
  * Help 1.0.3
  * kicadStepUpMod 10.17.1
  * Pyramids-and-Polyhedrons
  * Render 2024.1.23
  * sheetmetal 0.2.61
```

### Subproject(s) affected?

None

### Anything else?

[StativKopf_2.zip](https://github.com/user-attachments/files/16613049/StativKopf_2.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I can confirm.
@bgbsww could this be related to TNP changes for the mirror command?
@NomAnor could this be related to your changes?

**Comment by MarcusMWilliams** [comment]
Yes mirror was fixed

**Comment by bgbsww** [comment]
Can someone duplicate the "body is destroyed on recompute"?  When I try it, it just repairs the file and operates normally.

**Comment by amon-sha** [comment]
@bgbsww see https://github.com/FreeCAD/FreeCAD/issues/15881#issuecomment-2288905617

**Comment by maxwxyz** [comment]
@Panda631 So test with the next weekly on Friday please and if the issue is still present report back and we reopen this issue.

**Comment by Panda631** [comment]
> @Panda631 So test with the next weekly on Friday please and if the issue is still present report back and we reopen this issue.

After loading the model, the error messages are still present. The geometry looks OK, also after recomputing.

When I save the file and open it again, the errors have disappeared. I would say problem solved.
