### ISSUE TITLE
CAM: Pocket and MillFace safe and clearance height movement wrong

### ISSUE THREAD

**Issue by opensourcecnc** [FreeCAD/FreeCAD#16215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the pocket and millface operations movement throughout the operation when it's not cutting is done at clearance height, then the toolbit goes to safe height. After going through both heights, the toolbit is lowered at cutting position and continues the operation.
I will check the issue in other operations and modify the report if I find it happening elsewhere

![bug 5](https://github.com/user-attachments/assets/c3310801-a8cd-4329-9331-965f2f056bf9)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38555 (Git)
Build type: Release
Branch: main
Hash: 73cb5bafe0c32c178d9b594a6ca03124483d305f
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.65
  * AnimationFreeCAD
  * Assembly4 0.50.15
  * Curves 0.6.45
  * ExplodedAssembly-master
  * Movie 2024.2.15
  * pcb 6.2023.1
  * Render 2024.8.4
  * sheetmetal 0.4.24
  * woodworking 0.21.2.33771
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Probably this problem was fixed

<img width="647" height="404" alt="Image" src="https://github.com/user-attachments/assets/7720bdd4-2472-4b91-9c82-004d2f32e22b" />

**Comment by FEA-eng** [comment]
@tarman3 Can you confirm it should be closed?

**Comment by tarman3** [comment]
Yes

**Comment by opensourcecnc** [comment]
The problem is still there. In the screenshot, the movement towards the first hole should be done at 35 mm (clearance height, before the operation), then all the rapid movement should be done at 3 mm (safe height, during the operation). Instead, all the rapid movements are done at 35 mm.

![Image](https://github.com/user-attachments/assets/2598fe15-af0a-448d-b643-0d8ea576a95c)

**Comment by tarman3** [comment]
Please attach file

**Comment by opensourcecnc** [comment]
[lead in-out entrance offset problem.20251129-182954.zip](https://github.com/user-attachments/files/23834823/lead.in-out.entrance.offset.problem.20251129-182954.zip)
Sorry, here it is. I'm using the latest build on github: [Development Build weekly-2025.11.26](https://github.com/FreeCAD/FreeCAD/releases/tag/weekly-2025.11.26)

**Comment by tarman3** [comment]
> all the rapid movement should be done at 3 mm (safe height, during the operation).

As I know it is never be like you describe
In all operations movements between points is always at clearance height

You can use `MinTravel` to exclude retract

**Comment by opensourcecnc** [comment]
That's the way it should be, clearance between operations, safe inside the operation. Otherwise, why is there a safe height?

**Comment by tarman3** [comment]
Maybe situation will changed someday
https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Roadmap/ADR/ADR-008.md

**Comment by opensourcecnc** [comment]
From what I read there, there is a difference between the two values, even though some naming is improved. So the bug is still valid,

On the long term, taking that document as reference, the Clearance should not be a property of the operation anymore, but a property of the job (it should be consistent across the operations)
This leaves each operation with just the Retract Height.

It seems much more intuitive and logical this way, indeed.

**Comment by tarman3** [comment]
> the Clearance should not be a property of the operation anymore, but a property of the job

Agree only if processing one model in the `Job`
If there is several models in the `Job` or `Array`, I prefer to have ability to change `ClearanceHeight` for each operation

**Comment by sliptonic** [comment]
I've reopened the issue.  

The linked ADR just proposes the definition of the terms going forward.  Many parts of the application are still inconsistent with that definition and will be revised as we move forward.

The definition we're using in the ADR for clearance is the height to clear ALL stock, model, and clamps.

> Agree only if processing one model in the `Job`
> If there is several models in the `Job` or `Array`, I prefer to have ability to change `ClearanceHeight` for each operation

This would invalidate the definition above.  I can't understand how the height to clear everything will be different from one operation to the next.  Please tell me what the definition of ClearanceHeight is.

**Comment by tarman3** [comment]
At this moment we have only one height for travels between passes and operations, it is `ClearanceHeight`
For me looks terrible, if this height also will be one for all operations in Job 
I use 'big' `ClearanceHeight` only for first operation on model
 
All will changed than we get ability to set `retract height` for travels between passes

**Comment by opensourcecnc** [comment]
That's exactly what I was suggesting. One height to travel between operations, the clearance height, which should be at job level AND a retract height, at operation level, which controls the rapids between movements of the same operation

**Comment by tarman3** [comment]
Example with two `ClearanceHeight` values
One for Input and another for Output
Only first operation on model use big height
I do not need big height for travels between operations inside model

<img width="1041" height="395" alt="Image" src="https://github.com/user-attachments/assets/99be6af7-3773-40b0-b2dc-98efda80abfe" />

**Comment by opensourcecnc** [comment]
Why is this better than raising the toolbit at the end of the operation, move to the start of the next, raise it to clearance and continue? The travel distance is exactly the same...

<img width="1080" height="922" alt="Image" src="https://github.com/user-attachments/assets/4d701895-75e8-423c-a4d2-77ebb950851a" />

Anyway, for this type of situation, I think having a "between elements of the array" height on the array itself would be better...

If you want just the first movement, for the first element of the array, at big height, wouldn't a starting point be enough? And then you can use a low clearance height for all the movements. Or maybe use a custom op for that. Altering the normal (usual) behavior of clearance height is not a good thing, as far as normal users are concerned.

**Comment by tarman3** [comment]
> Why is this better than raising the toolbit at the end of the operation, move to the start of the next, raise it to clearance and continue? The travel distance is exactly the same...

No, it is not like you described
Probably because last Profile is closed

Another example

<img width="965" height="509" alt="Image" src="https://github.com/user-attachments/assets/cda743e7-3999-4673-a370-a1a9495a1f5f" />

**Comment by opensourcecnc** [comment]
Yes, I completely missed the profile. For this use case, I would suggest: make the clearance and retract behave the "normal" way. Add override options for start and end clearance height. Not sure if it's worth the hassle, but it can be helpful sometimes.

**Comment by tarman3** [comment]
> wouldn't a starting point be enough

You can not set only Z
You need to set 3 coordinates
And if something changed in model, you will need to find correct position again

**Comment by tarman3** [comment]
> make the clearance and retract behave the "normal" way

But this already done by expression
By default we can change `ClearanceHeight` for all operations from `SetupSheet`
Of course if expression was not removed

The only thing missing is `Retract`

**Comment by opensourcecnc** [comment]
I was talking about the proposed behavior in the document: clearance between operations, retract inside operations. And, if you need to change the clearance at the end of an operation to keep the tool lower, you could have a checkbox "override end clearance" where you set another value, specifically for that operation.

**Comment by tarman3** [comment]
Agree
Your description looks perfect for me
#25650

**Comment by opensourcecnc** [comment]
Yes, that's exactly it. One for the start would also be good (I believe the implementation is easy, once you did it for the end)

**Comment by tarman3** [comment]
<img width="1277" height="332" alt="Image" src="https://github.com/user-attachments/assets/fed11125-c256-4a0e-aa58-630481fb4351" />

**Comment by tarman3** [comment]
> Anyway, for this type of situation, I think having a "between elements of the array" height on the array itself would be better...

PS Tried this way in #23606,
but #25650 give more flexibility, also code is simpler

**Comment by sliptonic** [comment]
> Only first operation on model use big height
> I do not need big height for travels between operations inside model

This potentially crashes if the user selects "order by operation" in the job setup and has multiple fixtures.

using a lower height for travels between targets in the same operation makes sense, but traveling between operations is more dangerous because the operation doesn't know what came before or after it.

> The only thing missing is `Retract`

Isn't 'retract' just a renamed 'Safe Height'?


>> Anyway, for this type of situation, I think having a "between elements of the array" height on the array itself would be better...

Interesting idea.  
FWIW, I still worry that the entire concept of 'array' needs revisiting.  Current implementation is based on some assumptions that may not be valid.

**Comment by opensourcecnc** [comment]
I agree that Retract is just a different name, it should do what safe height does (or, in fact, doesn't) and be a property of the operation, just as safe height. Using this name seems much better, more intuitive.

I just noticed something about the array: there is the old array, but also a dress up with the same name. They generate different objects (the dressup has the base as child, while the separate array is right after the operation), but they look exactly the same. Is one of them going to go away?

**Comment by sliptonic** [comment]
Let's continue the discussion about array here: https://github.com/FreeCAD/FreeCAD/issues/25936
