### ISSUE TITLE
UI/UX: Default Light Theme Std_BoxSelection rectangle low contrast

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When working with with the default Light Theme set, the default Std_BoxSelection rectangle is almost not visible at all, due to low contrast to the white background (the rectantgle is yellow).

See screenshot:
![box-select-tool](https://github.com/user-attachments/assets/aa42f65d-5ba4-4bb5-81cc-1ce1dbd4383c)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@MisterMakerNL what PR should we link it to ?

**Comment by MisterMakerNL** [comment]
I dunno it is already in current release I think.

**Comment by luzpaz** [comment]
Thanks. Fixed in 1.1-dev

**Comment by semhustej** [comment]
I am not able to confirm it's fixed. Tested in latest weekly in safe mode:

![Image](https://github.com/user-attachments/assets/b60b1de9-da46-44a1-914d-d04de388e39f)

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.41866 (Git)
Build date: 2025/05/26 16:31:05
Build type: Release
Branch: main
Hash: bc5616dbf6cbe3a2d88992dc9572d6f5b5bb502f
Python 3.11.12, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/126.557/1.25

```

**Comment by semhustej** [comment]
I think the screenshot above from @MisterMakerNL  is from sketcher when editing existing sketch. I am not sure if this is `Std_BoxSelection` tool as when that tool is invoked from the menu, the color is different (yellow). The same happens when `Std_BoxSelection` is invoked outside of a sketch.

I think the issue is not resolved. Not being able to find a PR has a reason.

See behavior in the video:

https://github.com/user-attachments/assets/485e9b71-36e9-48cd-8573-92b08b2b7a04


Unrelated to the reported issue: the selection rectangle in sketcher has different color during sketch creation and editing of the sketch. It is visible in the video.

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42095 (Git)
Build date: 2025/06/06 16:36:48
Build type: Release
Branch: main
Hash: 9c017b0dbf538c2570df7c3316355cdcdc3163f5
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Revit/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1

```

**Comment by MisterMakerNL** [comment]
Can confirm this!
I probably cannot fix this with settings as both should have the same color off-course.

**Comment by semhustej** [comment]
@luzpaz could you please re-open this issue as it is not fixed yet?

**Comment by semhustej** [comment]
@maxwxyz 
Would it be possible for you to open this issue as it is not fixed yet?

**Comment by semhustej** [comment]
The issue is still valid.

**Comment by maxwxyz** [comment]
Fixed
