### ISSUE TITLE
Import: exported step model is scaled after gmsh meshing

### ISSUE THREAD

**Issue by matsievskiysv** [FreeCAD/FreeCAD#18980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Exported step model is scaled by 1000 after gmsh meshing, when both are used in the same python session.

The following code imports some FreeCAD model, exports it to STEP format, meshes it in GMSH and then repeats the process (part of workflow for automated geometry optimization).

The file is exported scaled by 1000 after GMSH mesh generation. After session reset, file scale is back to normal.

Setting `Part.exportUnits` to different value does not help the situation.

```python
import FreeCAD
import Import
import Part
import gmsh
import gc

def show_line(file, start):
    with open(file, 'r') as f:
        for line in f.readlines():
            if line.startswith(start):
                print(line)
                break


doc = FreeCAD.openDocument('/usr/local/share/examples/PartDesignExample.FCStd')
body = doc.findObjects(Type='PartDesign::Body')[0]

Part.exportUnits('MM')
Import.export([body], '/tmp/out.step')
FreeCAD.closeDocument(doc.Name)
del body
del doc
gc.collect()

# inspect some point coordinates
show_line('/tmp/out.step', '#25 =')

gmsh.initialize()
gmsh.option.setString('Geometry.OCCTargetUnit', 'M')
gmsh.model.add('model')
gmsh.merge('/tmp/out.step')
gmsh.model.mesh.generate(2)
gmsh.write('/tmp/out.msh')
gmsh.finalize()

doc = FreeCAD.openDocument('/usr/local/share/examples/PartDesignExample.FCStd')
body = doc.findObjects(Type='PartDesign::Body')[0]

Part.exportUnits('MM')
Import.export([body], '/tmp/out.step')
FreeCAD.closeDocument(doc.Name)

# inspect the same point coordinates
show_line('/tmp/out.step', '#25 =')
```

### Full version info

Discovered in [Debian packaged v0.20.2](https://packages.debian.org/bookworm/freecad), reproduced in build from source v1.0.0 and [latest main branch commit](https://github.com/FreeCAD/FreeCAD/commit/558eb19103518090d494fcde0e8deabba830f734)

### Subproject(s) affected?

Other (specify in description)

### Anything else?

Issue is not present in ImportGui

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oursland** [comment]
I'm experiencing 1000x scaling with OCCT 7.8.1, but not with OCCT 7.7.2.  I suspect that may be the underlying cause.

**Comment by colt45s1911a1** [comment]
i'm having a similar problem when exporting. 

OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * fasteners 0.5.37
  * sheetmetal 0.7.5


[scale problem.zip](https://github.com/user-attachments/files/18607902/scale.problem.zip)

**Comment by FEA-eng** [comment]
@matsievskiysv I can't run this script on Windows. Can you confirm if the issue is still relevant?

**Comment by colt45s1911a1** [comment]
This was fixed in an update. Or I'm no longer having the problem so I'm considering it solved.

**Comment by matsievskiysv** [comment]
I still observe the issue. Here's the dockerfile I've used to compile the latest FreeCAD (I've taken it from my project, so it's most certainly not the minimal one).

<details>

<summary><code>freecad.dockerfile</code></summary>

```dockerfile
FROM debian:trixie

ARG DEBIAN_FRONTEND=noninteractive
ARG BUILD_DIR=/tmp/build

RUN apt-get update -q \
    && apt-get install -qy --no-install-recommends \
    build-essential \
    cmake \
    git \
    libboost-date-time-dev \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-iostreams-dev \
    libboost-program-options-dev \
    libboost-python-dev \
    libboost-regex-dev \
    libboost-serialization-dev \
    libboost-thread-dev \
    libboost-timer-dev \
    libcoin-dev \
    libeigen3-dev \
    libffi-dev \
    libgl1-mesa-dri \
    libgts-bin \
    libgts-dev \
    libhdf5-openmpi-dev \
    libkdtree++-dev \
    libmed-dev \
    libmedc-dev \
    libocct-data-exchange-dev \
    libocct-ocaf-dev \
    libocct-visualization-dev \
    libopencv-dev \
    libpetsc-complex-dev \
    libproj-dev \
    libpugixml-dev \
    libpyside2-dev \
    libqt5opengl5-dev \
    libqt5svg5-dev \
    libqt5x11extras5-dev \
    libqt5xmlpatterns5-dev \
    libshiboken2-dev \
    libspdlog-dev \
    libspnav-dev \
    libvtk9-dev \
    libx11-dev \
    libxerces-c-dev \
    libyaml-cpp-dev\
    libzipios++-dev \
    occt-draw \
    pybind11-dev \
    pyside2-tools \
    python3-cffi \
    python3-dev \
    python3-gmsh \
    python3-packaging \
    python3-pip \
    python3-pivy \
    python3-ply \
    python3-pyside2.qtcore \
    python3-pyside2.qtgui \
    python3-pyside2.qtnetwork \
    python3-pyside2.qtsvg \
    python3-pyside2.qtwidgets \
    python3-pytest \
    qtbase5-dev \
    qttools5-dev \
    qtwebengine5-dev \
    swig \
    xvfb \
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH_TO_FREECAD_LIBDIR=/usr/lib/freecad-python3/lib/

ARG FREECAD_URL=https://github.com/FreeCAD/FreeCAD.git
ARG FREECAD_COMMIT=be93298afdc483a9f185c8471bbf8ce23e804149
RUN mkdir ${BUILD_DIR} \
    && cd ${BUILD_DIR} \
    && git init --initial-branch=master \
    && git remote add origin ${FREECAD_URL} \
    && git fetch origin ${FREECAD_COMMIT} \
    && git reset --hard FETCH_HEAD \
    && git submodule update --init --recursive \
    && cmake -S . -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -DBUILD_GUI=ON \
    -DFREECAD_BUILD_DEBIAN=OFF \
    -DBUILD_WITH_CONDA=OFF \
    -DINSTALL_TO_SITEPACKAGES=ON \
    -DBUILD_QT5=ON \
    -DFREECAD_USE_PYBIND11=ON \
    && cmake --build build -j$(nproc) \
    && cmake --install build \
    && cd / \
    && rm -rf ${BUILD_DIR}

RUN pip install --break-system-packages \
    jupytercad-freecad==3.0.0 \
    jupyterlab-spellchecker==0.8.4 \
    jupyterlab==4.4.7 \
    nbconvert==7.16.6 \
    python-lsp-server[all]==1.13.1

RUN find /usr/local/Mod/ -maxdepth 1 -type d \
    > /usr/lib/python3/dist-packages/freecad.pth \
    && echo /usr/local/lib \
    >> /usr/lib/python3/dist-packages/freecad.pth

RUN useradd -m user \
    && mkdir /home/user/work \
    && chown user:user /home/user/work

ENV JUPYTER_PASSWORD=password
USER user
ENV SHELL=/bin/bash
CMD jupyter lab --ip=0.0.0.0 --port=8888 --notebook-dir=/home/user --no-browser --NotebookApp.token $JUPYTER_PASSWORD
WORKDIR /home/user
EXPOSE 8888
```

</details>

Build and start the container with the command

```bash
docker build -f freecad.dockerfile --tag freecad:latest .
docker run --rm -it -p 8888:8888 freecad:latest
```

Login to https://127.0.0.1:8888 (password: password), paste the snippet from the issue into the new notebook and execute.

I get the output
```
#25 = CARTESIAN_POINT('',(20.358962517357,20.,-100.));
...
#25 = CARTESIAN_POINT('',(2.035896251736E+04,2.E+04,-1.E+05));
```

**Comment by matsievskiysv** [comment]
I've checked the same dockerfile, based on debian sid distribution and confirmed that issue is present there too.

**Comment by FEA-eng** [comment]
I can't test it with this script on Windows, but it should still be relevant as stated by @matsievskiysv.

**Comment by matsievskiysv** [comment]
I've updated dockerfile to build with QT6. The issue is still there.

<details><summary><code>freecad.dockerfile</code></summary>

```dockerfile
FROM debian:sid

ARG DEBIAN_FRONTEND=noninteractive
ARG BUILD_DIR=/tmp/build

RUN apt-get update -q \
    && apt-get install -qy --no-install-recommends \
    build-essential \
    cmake \
    git \
    libboost-date-time-dev \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-iostreams-dev \
    libboost-program-options-dev \
    libboost-python-dev \
    libboost-regex-dev \
    libboost-serialization-dev \
    libboost-thread-dev \
    libboost-timer-dev \
    libcoin-dev \
    libeigen3-dev \
    libffi-dev \
    libgl1-mesa-dri \
    libgts-bin \
    libgts-dev \
    libharfbuzz-dev \
    libhdf5-openmpi-dev \
    libkdtree++-dev \
    libmed-dev \
    libmedc-dev \
    libocct-data-exchange-dev \
    libocct-ocaf-dev \
    libocct-visualization-dev \
    libopencv-dev \
    libpcl-dev \
    libpetsc-complex-dev \
    libproj-dev \
    libpugixml-dev \
    libpyside6-dev \
    libshiboken6-dev \
    libspdlog-dev \
    libspnav-dev \
    libtool \
    libvtk9-dev \
    libx11-dev \
    libxerces-c-dev \
    libyaml-cpp-dev\
    libzipios++-dev \
    lsb-release \
    occt-draw \
    pybind11-dev \
    pyqt6-dev-tools \
    pyside6-tools \
    python3-cffi \
    python3-dev \
    python3-gmsh \
    python3-lark \
    python3-matplotlib \
    python3-packaging \
    python3-pip \
    python3-pivy \
    python3-ply \
    python3-pyside6.qtcore \
    python3-pyside6.qtgui \
    python3-pyside6.qtnetwork \
    python3-pyside6.qtsvg \
    python3-pyside6.qtwebchannel \
    python3-pyside6.qtwebenginecore \
    python3-pyside6.qtwebenginequick \
    python3-pyside6.qtwebenginewidgets \
    python3-pyside6.qtwidgets \
    python3-pytest \
    qt6-base-dev \
    qt6-svg-dev \
    qt6-tools-dev \
    qt6-webengine-dev \
    swig \
    xvfb \
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH_TO_FREECAD_LIBDIR=/usr/lib/freecad-python3/lib/

ARG FREECAD_URL=https://github.com/FreeCAD/FreeCAD.git
ARG FREECAD_COMMIT=c71c15c00971892ab5d4d24f1ed989c4e5ba537d
RUN mkdir ${BUILD_DIR} \
    && cd ${BUILD_DIR} \
    && git init --initial-branch=master \
    && git remote add origin ${FREECAD_URL} \
    && git fetch origin ${FREECAD_COMMIT} \
    && git reset --hard FETCH_HEAD \
    && git submodule update --init --recursive \
    && cmake -S . -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -DBUILD_GUI=ON \
    -DFREECAD_BUILD_DEBIAN=OFF \
    -DBUILD_WITH_CONDA=OFF \
    -DINSTALL_TO_SITEPACKAGES=ON \
    -DBUILD_QT6=ON \
    -DFREECAD_USE_PYBIND11=ON \
    && cmake --build build -j$(nproc) \
    && cmake --install build \
    && cd / \
    && rm -rf ${BUILD_DIR}

RUN pip install --break-system-packages \
    jupytercad-freecad==3.0.0 \
    jupyterlab-spellchecker==0.8.4 \
    jupyterlab==4.4.7 \
    nbconvert==7.16.6 \
    python-lsp-server[all]==1.13.1

RUN find /usr/local/Mod/ -maxdepth 1 -type d \
    > /usr/lib/python3/dist-packages/freecad.pth \
    && echo /usr/local/lib \
    >> /usr/lib/python3/dist-packages/freecad.pth

RUN useradd -m user \
    && mkdir /home/user/work \
    && chown user:user /home/user/work

ENV JUPYTER_PASSWORD=password
USER user
ENV SHELL=/bin/bash
CMD jupyter lab --ip=0.0.0.0 --port=8888 --notebook-dir=/home/user --no-browser --NotebookApp.token $JUPYTER_PASSWORD
WORKDIR /home/user
EXPOSE 8888
```

</details>

```bash
docker build -f freecad.dockerfile --tag freecad:latest .
docker run --rm -it -p 8888:8888 freecad:latest
```
