### ISSUE TITLE
Add-on Manager freezes or hangs

### ISSUE THREAD

**Issue by bankh** [FreeCAD/FreeCAD#22302]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

FreeCAD Add-on Manager freezes or hangs.

[Addon Manager Freezing](https://forum.freecad.org/viewtopic.php?p=834618#p834618)

### Full version info

```shell
OS: Ubuntu 22.04.5 LTS (xcb)
Architecture: x86_64
Version: 1.0.1.39285 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.1)
Hash: 878f0b8c9c72c6f215833a99f2762bc3a3cf2abd
Python 3.11.12, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Problem
When the AddonManager encounters a corrupted package.xml file, the error-handling code crashes with an `AttributeError` instead of showing a helpful error message about the XML problem.

### What happens
1. AddonManager tries to parse a package.xml file
2. The XML parsing fails with: `RuntimeError: No 'package' element found in metadata file`
3. Error handler tries to execute: `fci.Console.PrintWarning(f" {self.name}... ignoring the bad data.\n")`
4. Crashes with: `AttributeError: 'UpdateMetadataCacheWorker' object has no attribute 'name'`

### Result
Users see a confusing AttributeError instead of the actual XML parsing error, making it impossible to understand what went wrong.

### Error trace
AttributeError: 'UpdateMetadataCacheWorker' object has no attribute 'name'

### Location
`src/Mod/AddonManager/addonmanager_workers_installation.py`, line 197

### Impact
- Error handling is broken
- Real XML parsing issues are masked
- Users can't understand what failed
- Debugging becomes impossible

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bankh** [comment]
## Solution

**File:** `src/Mod/AddonManager/addonmanager_workers_installation.py`  
**Method:** `UpdateMetadataCacheWorker.process_package_xml`

### Current (broken) code:
```python
try:
    metadata = MetadataReader.from_file(new_xml_file)
except xml.etree.ElementTree.ParseError:
    fci.Console.PrintWarning("An invalid or corrupted package.xml file was downloaded for")
    fci.Console.PrintWarning(f" {self.name}... ignoring the bad data.\n")
    return
```

### Fixed code:
```python
try:
    metadata = MetadataReader.from_file(new_xml_file)
except (xml.etree.ElementTree.ParseError, RuntimeError) as e:
    fci.Console.PrintWarning("An invalid or corrupted package.xml file was downloaded for")
    fci.Console.PrintWarning(f" {repo.name}... ignoring the bad data.\n")
    fci.Console.PrintWarning(f"Error details: {str(e)}\n")
    return
```

### Changes made:
1. **Fixed AttributeError:** Changed `self.name` to `repo.name`
2. **Expanded exception handling:** Now catches both `ParseError` and `RuntimeError` 
3. **Added diagnostic info:** Includes actual error details for better debugging

This fix handles both XML parsing failures and metadata validation errors while providing error messages.

**Comment by kevenwyld** [comment]
I'm having this issue as well, but I don't see a PR for it.  Was this fixed in the upstream addon manager?  I get the same failure in the latest nightly.

**Comment by bankh** [comment]
> I'm having this issue as well, but I don't see a PR for it. Was this fixed in the upstream addon manager? I get the same failure in the latest nightly.

@kevenwyld I did not make a PR or see something related to this one as a PR---except the post in the forum that I shared. I am sharing what I have done, and at the moment, it works for me in the highlighted configuration. If the people can confirm this fixes the freezing/ halting issue and is accepted as an appropriate solution, then I can initiate a PR.

**Comment by kevenwyld** [comment]
So at this moment all the linux versions of the application are producing this stack trace and hang when trying to search for addons on new installations with no cache.  It will never complete looking for addons and you have to kill the process.  I think this issue should be reopened.


https://github.com/user-attachments/assets/e393b344-aed0-45ca-823a-409d306ca210

**Comment by kevenwyld** [comment]
I tried your workaround, which for some reason does allow all the metadata to be downloaded, however I'm not sure that fixing it this way is the best solution.  But either way the issue should be in an open issue

**Comment by codypiersall** [comment]
Since this issue persists in main, it should be reopened. I just ran into it today.

**Comment by codypiersall** [comment]
I didn't realize that AddonManager is [its own repository](https://github.com/FreeCAD/AddonManager/)... I'll see if I can reproduce using that repository's main branch.

**Comment by codypiersall** [comment]
I'm not seeing this issue when building FreeCAD from source, using the main branch of AddonManager (after [some fixes to CMakeLists.txt](https://github.com/FreeCAD/AddonManager/pull/130)) so this issue I think is good to be closed—hopefully a new AppImage can be released soon!

**Comment by kevenwyld** [comment]
> I'm not seeing this issue when building FreeCAD from source, using the main branch of AddonManager (after [some fixes to CMakeLists.txt](https://github.com/FreeCAD/AddonManager/pull/130)) so this issue I think is good to be closed—hopefully a new AppImage can be released soon!

I'll test later, but did you remove all the assets before testing?  For me if I had metadata from an old installation it works, but if I remove it as it would be on a new install where freecad had never been used before, I would run into this issue.  ~~Someone in the addonmanager repo seems to think it's some bad assets like images or something from some of the 3rd party repos causing this problem.~~ EDIT: Nevermind, that's an unrelated issue.

**Comment by codypiersall** [comment]
I didn't do anything to try to remove any metadata from a previous install, but here's what I did do:

1. Install FreeCAD from the AppImage; it was the first FreeCAD installation I had on my current computer. First time I tried to use the addon manager, I ran into this issue.
2. Build FreeCAD from source, using everything just as it is in FreeCAD's `main` branch. I ran into this exact issue.
3. Updated the AddonManager subrepo to main, and after updating CMakeLists.txt so it would actually build, I did not run into this issue.

In the AddonManager repo, commit [ca1a785a6498c785d7ff8fd5c4d850a5f0524805](https://github.com/FreeCAD/AddonManager/commit/ca1a785a6498c785d7ff8fd5c4d850a5f0524805) actually removed the file that this [fix mentioned in this thread](https://github.com/FreeCAD/FreeCAD/issues/22302#issuecomment-3027488604) talks about.

**Comment by kevenwyld** [comment]
Something the addonmanager talks to when it looks for metadata got fixed I think, I can't reproduce this with the 1.0.1 official appimage anymore, even on a clean install.  No custom build necessary.
