### ISSUE TITLE
BIM: Shortcuts not displayed or usable for sub-menu items

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#22610]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Sub-menu items do not display a shortcut:
For example: Utils > Panel tools > Nest

The command has a shortcut (N, E), but it is not displayed or usable. The Panel command has a usable shortcut because it also occurs in the 3D/BIM menu.

This can be solved by creating sub-menus in a different manner. See:
https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Draft/draftutils/init_tools.py

EDIT: Although maybe that is more of a workaround and it would be better to fix the root cause.
EDIT2: Corrected the command example.

### Full version info

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.42564 (Git)
Build date: 2025/07/14 18:51:42
Build type: Release
Branch: main
Hash: dc2f2374b6ab3e3381653fad125b1b619bb49f7c
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Free Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
Installed mods:
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This is a regression compared to the V0.21 Arch WB.

**Comment by markkomartin** [comment]
> ..The command has a shortcut (P, C), but it is not displayed or usable. The Panel command has a usable shortcut because it also occurs in the 3D/BIM menu.
> 

If I'm not mistaken in BIM wb shortcut (P, C) is also used for Arch PipeConnector.
https://wiki.freecad.org/Arch_PipeConnector

If I try to use it I get the following message in the report view:
Please select exactly 2 or 3 Pipe objects

I get the same message even in stable version 1.0.1

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42523 (Git)
Build date: 2025/07/07 16:45:59
Build type: Release
Branch: main
Hash: d2a4f8994fba9e3e62098f1ff9a1af67e0ecf6e1
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/93.6146/1

**Comment by Roy-043** [comment]
Oops, I got mixed up and have used the wrong example. I'll correct the original issue.

**Comment by chennes** [comment]
@yorikvanhavre do you have a sense of when this might have broken?

**Comment by Roy-043** [comment]
The mentioned regression is due to the removal of the [init_tools.py](https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Draft/draftutils/init_tools.py) 'workaround' code when the unified BIM WB was created during the V1.0 dev cycle. The issue that grouped menu commands do not have shortcuts is older. I think I noticed this in V0.19, but it may have existed before that version.

**Comment by yorikvanhavre** [comment]
> The issue that grouped menu commands do not have shortcuts

Is that the case for all python-generated grouped commands? Indeed it might be better to fix the cause then...

**Comment by Roy-043** [comment]
> Is that the case for all python-generated grouped commands?

Yes, you can see this in the Assembly WB as well. The shortcut for "Insert New Part" ("P") does not work.

**Comment by Roy-043** [comment]
Should hopefully be fixed with #24043.

**Comment by furgo16** [comment]
That PR did fix the issue for C++ workbenches such as Sketcher:

<img width="466" height="160" alt="Image" src="https://github.com/user-attachments/assets/5efa5904-6f77-4472-9ebf-af6731d33d37" />
<img width="466" height="160" alt="Image" src="https://github.com/user-attachments/assets/da790487-9e52-447a-b097-16cb69c0f47b" />

However, the issue is still present in Python workbenches (e.g. BIM):

<img width="251" height="148" alt="Image" src="https://github.com/user-attachments/assets/0d6299bf-b683-4f53-9076-108ca7ee9a39" />
<img width="251" height="148" alt="Image" src="https://github.com/user-attachments/assets/1075e850-3520-4a1b-9e9b-fd01073ac32b" />

**Comment by matt-taylor-git** [comment]
I've created https://github.com/FreeCAD/FreeCAD/pull/24100 for review

**Comment by Roy-043** [comment]
Fixed with #24100.
