### ISSUE TITLE
Preferences: throws error due to corruption in user.cfg (1.1dev r42780)

### ISSUE THREAD

**Issue by sslupsky** [FreeCAD/FreeCAD#22858]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When attempting to save preferences an error is thrown:
"The selected asset path is not writable."

If I change a preference (Camera Type), the change appears to stick when the preference pane is opened again and through restarting FreeCAD. 

To recreate:

Start FreeCAD
Select Preferences
Click "Ok"

<img width="476" height="257" alt="Image" src="https://github.com/user-attachments/assets/abdb8a14-5f9a-4cf9-abe1-12ec8d7c6e68" />

### Full version info

```shell
OS: macOS 15.6
Architecture: x86_64
Version: 1.1.0dev.42780 (Git)
Build date: 2025/07/28 17:17:34
Build type: Release
Branch: main
Hash: 8dc6397fc4433785f73f8a1958ff11243c348376
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/Canada (en_CA)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Trackball/Object center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 72/109/1
Installed mods: 
  * sheetmetal 0.7.11
  * Curves 0.6.58
```

### Subproject(s) affected?

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sslupsky** [comment]
@luzpaz I went back and grabbed a copy of the old preferences from a backup and attached here if you want to try restoring these to recreate this issue and the Polyline issue reported in #22855 .

I scanned through them and it appears to me there is a corruption at line 816 in user.cfg.  I have no idea how the corruption occurred but I restored from a backup that shows the file was last modified on July 21.

I'll leave the issue open in case you want to track it further.  It might be worthwhile to consider what is done if a preferences file is found to be corrupted.  Otherwise feel free to close the issue.

[freecad preferences.zip](https://github.com/user-attachments/files/21537999/freecad.preferences.zip)

**Comment by halfdane** [comment]
Seems like the only "asset path" in the preferences are the CamAssets, and indeed creating the directory by copying it from the input field and running `mkdir -p ~/.config/FreeCAD/CamAssets` (Ubuntu 22.04) fixed the problem for me.

**Comment by sslupsky** [comment]
@halfdane Creating the directory (~/Library/Preferences/FreeCAD/CamAssets) resolved the issue for me on macOS.  Thank you.

**Comment by colinl** [comment]
Using the beta channel snap on Ubuntu I had to create ~/snap/freecad/common/CamAssets/, which is the default folder configured in Preferences > CAM > Assets

**Comment by FEA-eng** [comment]
@maxwxyz I think that this should be a blocker.

**Comment by maxwxyz** [comment]
isn't this the same as https://github.com/FreeCAD/FreeCAD/issues/23015

**Comment by FEA-eng** [comment]
> isn't this the same as [#23015](https://github.com/FreeCAD/FreeCAD/issues/23015)

I don't think so. That one doesn't mention the pop-up discussed here. It seems that there are 2 issues with Preferences caused by some CAM changes - errors appearing whenever the Preference Editor is opened and pop-up appearing whenever preferences changes are confirmed. Maybe they have the same cause but we should make sure both are fixed for 1.1.0. They are really nasty bugs (this one is probably even worse because you have to accept the pop-up).

**Comment by MisterMakerNL** [comment]
This is pretty big bug, since it doesn't go away until CAM wb is activated.
It basically breaks new installations.

**Comment by pmjdebruijn** [comment]
> Seems like the only "asset path" in the preferences are the CamAssets, and indeed creating the directory by copying it from the input field and running `mkdir -p ~/.config/FreeCAD/CamAssets` (Ubuntu 22.04) fixed the problem for me.

I have this issue on self built current git master as well, and the `mkdir` resolved the issue for me as well...

**Comment by ReneSci** [comment]
Just tested the latest weekly build

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/02 21:58:19
Build type: Release
Branch: main
Hash: 04e085cba3b43d1e09aedd4445824a6eb46e45b6
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US) [ OS: Danish/Denmark (da_DK) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Classic/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods: 
  * A2plus 0.4.68
  * CfdOF 1.31.10
  * Defeaturing 1.2.6
  * lattice2 1.0.0
  * Manipulator 1.6.0
  * MeshRemodel 1.10.38
  * OpenDark 2024.3.13
  * OpticsWorkbench 1.2.2
  * QuickMeasure 2022.10.28
  * sheetmetal 0.7.24
  * workfeature

```


Still : trying to change anything in the preferences and accept, I still get this:

<img width="383" height="209" alt="Image" src="https://github.com/user-attachments/assets/6097eb68-6c33-435b-af4a-6103a200d338" />


If I install the Current stable version: 1.0.2 - it seems to work ok, but as soon as I replaces the files with ones from the weekly build build - the error occurs....



Print out of messages:
```
11:20:09  default matplotlib import
11:20:11  Initializing A2plus Workbench v0.4.68.
11:20:35  Found addon not in main AM catalog: OpenDark
11:20:35  Found additional branch 'development' for addon AddonManager
11:20:35  Found additional branch 'development' for addon Assembly4.1
11:20:35  Unrecognized license string 'LGPLv2.1' normalized to SPDX license ID 'LGPL-2.1' for addon 'BCF Plugin'
11:20:35  Unrecognized license string 'LGPLv2.1' normalized to SPDX license ID 'LGPL-2.1' for addon 'boltsfc'
11:20:35  Unrecognized license string 'AGPLv3.0' normalized to SPDX license ID 'AGPL-3.0' for addon 'Defeaturing Workbench'
11:20:35  Unrecognized license string 'AGPLv3.0' normalized to SPDX license ID 'AGPL-3.0' for addon 'Defeaturing Workbench'
11:20:36  Unrecognized license string 'LGPLv3' normalized to SPDX license ID 'LGPL-3.0' for addon 'Dodo'
11:20:36  Unrecognized license string 'LGPLv2.1' normalized to SPDX license ID 'LGPL-2.1' for addon 'ElectroMagnetic Workbench'
11:20:36  Unrecognized license string 'LGPLv3' normalized to SPDX license ID 'LGPL-3.0' for addon 'FrameForge'
11:20:36  Unrecognized license string 'lgpl-2.1-or-later' normalized to SPDX license ID 'LGPL-2.1-or-later' for addon 'Gridfinity Workbench'
11:20:36  Unrecognized license string 'AGPLv3.0' normalized to SPDX license ID 'AGPL-3.0' for addon 'KicadStepUp Workbench'
11:20:36  Unrecognized license string 'LGPL-3' normalized to SPDX license ID 'LGPL-3.0' for addon 'Maker Workbench'
11:20:36  Unrecognized license string 'GPLv3.0' normalized to SPDX license ID 'GPL-3.0' for addon 'Manipulator Workbench'
11:20:36  Unrecognized license string 'GPLv3.0' normalized to SPDX license ID 'GPL-3.0' for addon 'Manipulator Workbench'
11:20:36  Could not resolve property : #%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82_114
11:20:36  Could not resolve property : #%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82_114
11:20:36  Unrecognized SPDX license ID specified for addon 'MOOC': 'GPLv2.1'
11:20:36  Unrecognized license string 'GPL-3' normalized to SPDX license ID 'GPL-3.0' for addon 'NikraDAP'
11:20:36  Unrecognized license string 'AGPLv3.0' normalized to SPDX license ID 'AGPL-3.0' for addon 'FreeCAD-PCB'
11:20:36  Unrecognized SPDX license ID specified for addon 'SearchBar': 'CCOv1'
11:20:36  Unrecognized SPDX license ID specified for addon 'Woodworking': 'MIT, keep author tag without change.'
11:20:36  Unrecognized license string 'LGPLv2.1' normalized to SPDX license ID 'LGPL-2.1' for addon 'Yaml Workbench'
11:20:49  Cannot find icon: preferences-cam
11:20:49  Traceback (most recent call last):
11:20:49    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Main\Gui\PreferencesJob.py", line 40, in __init__
11:20:49      self.form = FreeCADGui.PySideUic.loadUi(":preferences/PathJob.ui")
11:20:49                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:20:49    File "<string>", line 4, in <module>
11:20:49  RuntimeError: Cannot open file
11:20:49  JobPreferencesPage is not a preference page
11:20:49  Traceback (most recent call last):
11:20:49    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Base\Gui\PreferencesAdvanced.py", line 35, in __init__
11:20:49      self.form = FreeCADGui.PySideUic.loadUi(":preferences/Advanced.ui")
11:20:49                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:20:49    File "<string>", line 4, in <module>
11:20:49  RuntimeError: Cannot open file
11:20:49  AdvancedPreferencesPage is not a preference page
11:24:32  Cannot find icon: preferences-cam
11:24:32  Traceback (most recent call last):
11:24:32    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Main\Gui\PreferencesJob.py", line 40, in __init__
11:24:32      self.form = FreeCADGui.PySideUic.loadUi(":preferences/PathJob.ui")
11:24:32                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:24:32    File "<string>", line 4, in <module>
11:24:32  RuntimeError: Cannot open file
11:24:32  JobPreferencesPage is not a preference page
11:24:32  Traceback (most recent call last):
11:24:32    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Base\Gui\PreferencesAdvanced.py", line 35, in __init__
11:24:32      self.form = FreeCADGui.PySideUic.loadUi(":preferences/Advanced.ui")
11:24:32                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:24:32    File "<string>", line 4, in <module>
11:24:32  RuntimeError: Cannot open file
11:24:32  AdvancedPreferencesPage is not a preference page
11:27:06  QTextBrowser: No document for file:///C:%5CFreecad-current%5CFreeCAD_weekly-build%5Cdoc%5C/ThirdPartyLibraries.html
```

**Comment by ReneSci** [comment]
Did this (Windows 11):
1) Installed the latest release/stable version 1.02 by using the installer. The "Preferences" is working.
2) Made a back-up copy of the whole "CAM" directory structure from the above installation:
     C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM
3) Copied all the files from the latest weekly build "FreeCAD_weekly-2025.09.03-Windows-x86_64-py311.7z" into
     C:\Freecad-current\FreeCAD_weekly-build\   
       (Normally I delete all files from this directory before copying the latest weekly into it)
    -> Now "Preferences" does not work.
4) Copied the files from my back-up of the "CAM" directory (the "CAM" files from stable version 1.01) back to
    C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM

And then "Preferences" works....

Can this story give a clue on whats wrong ?

**Comment by ReneSci** [comment]
Just tested the latest knightly build

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/16 20:38:23
Build type: Release
Branch: main
Hash: bac49e465908071e7400a547eb813bc5017ae7dc
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US) [ OS: Danish/Denmark (da_DK) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Classic/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods: 
  * A2plus 0.4.68
  * CfdOF 1.32.1
  * Defeaturing 1.2.9
  * freecad.optics_design_workbench 0.6.2
  * Manipulator 1.6.2
  * OpenDark 2024.3.13
  * OpticsWorkbench 1.2.2
  * QuickMeasure 2022.10.28
  * sheetmetal 0.7.52
  * toSketch 1.0.1
  * workfeature

```

It works, but sill drops some error messages:

```
16:11:33  default matplotlib import
16:12:02  Cannot find icon: preferences-cam
16:12:02  Traceback (most recent call last):
16:12:02    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Main\Gui\PreferencesJob.py", line 40, in __init__
16:12:02      self.form = FreeCADGui.PySideUic.loadUi(":preferences/PathJob.ui")
16:12:02                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:12:02    File "<string>", line 4, in <module>
16:12:02  RuntimeError: Cannot open file
16:12:02  JobPreferencesPage is not a preference page
16:12:02  Traceback (most recent call last):
16:12:02    File "C:\Freecad-current\FreeCAD_weekly-build\Mod\CAM\Path\Base\Gui\PreferencesAdvanced.py", line 35, in __init__
16:12:02      self.form = FreeCADGui.PySideUic.loadUi(":preferences/Advanced.ui")
16:12:02                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:12:02    File "<string>", line 4, in <module>
16:12:02  RuntimeError: Cannot open file
16:12:02  AdvancedPreferencesPage is not a preference page
16:14:09  camassets.INFO: CAM asset directory changed in preferences: User parameter:BaseApp/Preferences/Mod/CAM/Tools ToolPath C:\Users\xxxx\AppData\Roaming\FreeCAD\v1-1\CamAssets


```

**Comment by chennes** [comment]
Those error messages were eliminated by a PR we merged yesterday, so should be gone in next week's build.

**Comment by ReneSci** [comment]
Yes, it is ok now

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/23 18:47:15
Build type: Release
Branch: main
Hash: e9ce06155d8d47aad7d6c079bfa8ba54df2b6081
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US) [ OS: Danish/Denmark (da_DK) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Classic/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods: 
  * A2plus 0.4.68
  * CfdOF 1.32.1
  * Defeaturing 1.2.9
  * freecad.optics_design_workbench 0.6.2
  * Manipulator 1.6.2
  * OpenDark 2024.3.13
  * OpticsWorkbench 1.2.2
  * QuickMeasure 2022.10.28
  * sheetmetal 0.7.52
  * toSketch 1.0.1
  * workfeature

```
