### ISSUE TITLE
Core: Drag and Drop Body between Part and Origin adjust its Placement

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#23824]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Drag and Drop of an object (e.g. body) between a Part and its origin object adjusts the placement property of the dragged object if sync placement is checked.

Demo:

https://github.com/user-attachments/assets/4f88ea67-dba3-4ec0-8d66-dd513a7cadb8

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/09 06:43:51
Build type: Release
Branch: main
Hash: c1dd116e1e3304511d9e5e634e711e549b2b84e7
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/133.772/2
Installed mods: 
  * AddonManager 2025.8.16
  * Cables 0.2.1
  * CurvedShapes 1.0.13
  * Defeaturing 1.2.6
  * dodo 1.0.1
  * freecad.gears 1.3.0
  * Gridfinity 0.11.9
  * Manipulator 1.6.0
  * OpticsWorkbench 1.2.2
  * Rocket 4.1.1
  * sheetmetal 0.7.24
  * Silk 0.2.0
  * Telemetry 1.0.2
```

### Subproject(s) affected?

Core

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke FYI

**Comment by maxwxyz** [comment]
@FEA-eng I'm not able to reproduce, can you?

**Comment by FEA-eng** [comment]
> [@FEA-eng](https://github.com/FEA-eng) I'm not able to reproduce, can you?

I can still reproduce it:

<img width="894" height="584" alt="Image" src="https://github.com/user-attachments/assets/ac2e411c-7415-4863-b7f1-104d54366932" />

```
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260519 (Git shallow)
Build date: 2026/05/19 20:59:45
Build type: Release
Branch: (HEAD detached at 5a5d8d042)
Hash: 5a5d8d0425fdb440fb5dcb47f1c48422d07d3267
Python 3.11.15, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL) [ OS: Polish/Poland (pl_PL) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
```

**Comment by maxwxyz** [comment]
mh I cannot drag it between the part and origin anymore...
Does it also happen when you drag it onto the part object?

**Comment by FEA-eng** [comment]
> Does it also happen when you drag it onto the part object?

No, only when dropping it onto the Part's Origin.

**Comment by ipatch** [comment]
> mh I cannot drag it between the part and origin anymore... Does it also happen when you drag it onto the part object?

i find it very sensitive to be able to drag "between" objects in the tree. not even sure what the intended behavior of that is. 

i've been troubleshooting this issue for a couple of hours now, and getting reproducible results is a bit confusing. because in that last gif @FEA-eng posted he's dragging the "body" **ontop** of the origin and **not** in between the **origin** and **part** labels. 

where as @maxwxyz in your original video you are dragging the "body" **inbetween** the part's **origin** label and the part's **label** itself in the tree view.

**Comment by VishalRamKN** [comment]
Hey @maxwxyz I stumbled upon this issue as I was following #29475 

I tried to reproduce this issue on the latest dev build, but I couldn't. As @ipatch mentions, @maxwxyz's verison of the issue is different from what @FEA-eng is experiencing. I tried both and I was not able to reproduce it. (Both are kinda same?) Perhaps, this bug was fixed? @FEA-eng Do confirm. I'm attaching the version details along with the video of the working.

## Video trying to reproduce the issue in the current dev build

https://github.com/user-attachments/assets/de45abbb-5cfc-43ac-9f2c-edb3c1dbc1f8

As we can see, I am not able to reproduce the issue

## Version Details

```
OS: Fedora Linux 43 (Workstation Edition) (GNOME/gnome/wayland)
Architecture: x86_64
Version: 26.3.0dev.48858 (Git)
Build date: 2026/09/22 13:40:00
Build type: Release
Branch: main
Hash: 7e947f48af2a97bb8be4d2bb2a0af0d46053ce66
Python 3.14.7, Qt 6.10.3, Coin 4.0.10 (bundled), Pivy 0.6.11 (bundled), Vtk , boost 1_83, Eigen3 3.4.0, PySide 6.10.3
shiboken 6.10.3, xerces-c 3.3.0, Clipper2 , OCC 7.9.3
Locale: English/India (en_IN)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
QPA/File dialog/Color dialog: wayland/via Qt/via Qt
Navigation Style/Orbit Style/Rotation Mode: CAD/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/143.907/1
OpenGL version/vendor/renderer: 4.6 (Compatibility Profile) Mesa 25.3.6/Intel/Mesa Intel(R) Graphics (ADL GT2)
Installed mods:
  * Curved Shapes 1.0.15
  * Curves workbench 0.6.75
  * SheetMetal Workbench 0.8.21
  * freecad.gears workbench 1.3.0
```

**Comment by FEA-eng** [comment]
I still have this issue.

<img width="933" height="386" alt="Image" src="https://github.com/user-attachments/assets/417b87e9-35f7-46f8-b4a0-ef70a3aacd33" />

```
OS: Windows 11 build 26200
Architecture: x86_64
Version: 26.3.0dev.20260916 (Git shallow)
Build date: 2026/09/16 06:32:59
Build type: Release
Branch: (HEAD detached at a4ce44d33)
Hash: a4ce44d33b7e42e16cb8156058a1894237042ab4
Python 3.11.14, Qt 6.8.3, Coin 4.0.10 (bundled), Pivy 0.6.11 (bundled), Vtk 9.3.0, boost 1_84, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.0.0, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
QPA/File dialog/Color dialog: windows/via Win32/via Qt
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
OpenGL version/vendor/renderer: 4.6.0 NVIDIA 617.14/NVIDIA Corporation/NVIDIA GeForce RTX 5080/PCIe/SSE2
```
