### ISSUE TITLE
Sketcher: Constraint icons selection not possible

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#25840]
### Workbench affected?

Sketcher

### Problem description

Currently, constraints that define dependencies for a "point" are often placed in the background (obscured by lines). As a result, there's no way to select these constraints in the 3D viewport (for example, to delete a constraint).

The only way to select a constraint is to somehow find it in a filter. This is practically impossible if the sketch is even slightly complex.
Or, you have to move the line that overlaps the constraint.

Video demonstration

https://github.com/user-attachments/assets/8501ebeb-f939-49c6-b1e2-b023e26cc5fc

Now

![Image](https://github.com/user-attachments/assets/a20369db-eee7-49cc-ad96-f7822fdcc3e5)

Should be

![Image](https://github.com/user-attachments/assets/bccf0647-8a00-45ab-a47a-358fcb31dbcc)

UPD / This problem is also common with equality and symmetry constraints. (There may be others, but I haven't tried all the possible ones.)

![Image](https://github.com/user-attachments/assets/23831423-9e10-49df-89ef-d5f89b0846c0)

### Steps to reproduce

---

### Expected behavior

---

### Actual behavior

---

### Development version About Info (in Safe Mode)

```shell
---
```

### Last known good version (optional)

![Image](https://github.com/user-attachments/assets/a60669f1-63f2-4d9d-887f-840c6d26b43e)

```shell
---
```

**Comment by maxwxyz** [comment]
@tetektoza this is the z depth buffer you wanted to introduce, correct?

**Comment by ipatch** [comment]
> [@tetektoza](https://github.com/tetektoza) this is the z depth buffer you wanted to introduce, correct?

is this not a regression? i am able to reproduce this error with the latest dev build. and do not experience this issue with the v1.0.2 release of freecad.

FWIW i'm actively bisecting this issue.

**Comment by ipatch** [comment]
10x bisects later

https://github.com/FreeCAD/FreeCAD/commit/02716069c2acba90780a34d7a0ed260360b5095

at some point it was the desired behavior to render the lines over the constraints.

**Comment by maxwxyz** [comment]
this was not an error but intentional as the dimension lines always covered the geometry. IIRC @tetektoza wanted to adjust or create a separate zdepth so that the text is always in the front

**Comment by kaiwas** [comment]
> this was not an error but intentional as the dimension lines always covered the geometry.

It's a strange decision. Because choosing constraints is practically impossible right now.

**Comment by ipatch** [comment]
> > this was not an error but intentional as the dimension lines always covered the geometry.
> 
> It's a strange decision. Because choosing constraints is practically impossible right now.

i'd agree with that to. in certain situations it is difficult to select a constraint depending on how the lines are laid out.

**Comment by ElPatoNoEsTu** [comment]
How about adding an handle to the constraints so there is something to - where to grab/select it in ambigous cases?

**Comment by kaiwas** [comment]
My personal opinion is that the problem is very serious.
I would mark it as a "blocker," but the issue doesn't even have a bug label right now.

To understand how bad it is, just make a slightly complex sketch and try changing the constraints.
This behavior should in no way be considered production-ready.

**Comment by ElPatoNoEsTu** [comment]
@maxwxyz, @PaddleStroke  - might we please reevaluate this topic to Bug / Blocker for 1.1 ... imho its nothing wrong with rendering geometry on top but if this prevents the selection of constraints - this might be a serious problem.

**Comment by kaiwas** [comment]
> if this prevents the selection of constraints

Yes. The problem is not in the display itself, but in the choice of constraints that overlap the line.

**Comment by maxwxyz** [comment]
I think @tetektoza is already working on it hopefully it will be fixed for 1.1

**Comment by ElPatoNoEsTu** [comment]
Hi Max,  @maxwxyz - while @tetektoza  hopefully adresses this - this is no feature - this needs to be treated as bug due to its impact on usability...

**Comment by ipatch** [comment]
seems to be it would make sense to introduce a setting in the sketcher preferences to allow the old or new behavior depending on what the user prefers.

**Comment by maxwxyz** [comment]
PR is up, I'm building right now to test it right away. No need to panic 😄

**Comment by nishendra3** [comment]
> The selection issue hasn't been fixed. Only the visual arrangement of the constraint icons has changed. Please reopen the issue. The current version is very inconvenient, despite the visual improvements.

Can you describe more clearly what's the current issue ? Are the constraints still not selectable ? If you can provide an example file it would be really useful

**Comment by kaiwas** [comment]
@maxwxyz Thank you!

**Comment by maxwxyz** [comment]
After testing a bit it only happens if the Sketch is on the XY-plane and a slight rotation makes it possible to select it:

https://github.com/user-attachments/assets/34b24f47-fe4f-4fcc-8044-4c812cc56c30

**Comment by FEA-eng** [comment]
@maxwxyz Could it be a release blocker? It doesn't work in the most common initial state of a sketch.

**Comment by maxwxyz** [comment]
I don't think so, we released 1.1 with it. @tritao do you want to look at this?

**Comment by maxwxyz** [comment]
I am not able to reproduce it on latest weekly anymore. @kaiwas please provide an example file

**Comment by kaiwas** [comment]
> I am not able to reproduce it on latest weekly anymore. [@kaiwas](https://github.com/kaiwas) please provide an example file

You may have a more recent weekly build. However, the May 20th build still has this issue.
Video demonstration in Safe Mode

https://github.com/user-attachments/assets/cae74a89-4193-4d1b-8ecc-257522c2cd2a

file

[Teeest.FCStd.remove.zip](https://github.com/user-attachments/files/28228290/Teeest.FCStd.remove.zip)

**Comment by maxwxyz** [comment]
I cannot reproduce with the file and video on latest weekly, maybe a Windows issue? @pierreporte do you have Windows?
This is my attempt:

https://github.com/user-attachments/assets/3cd30ed7-40bd-4d06-b3fa-f3732c72c161

**Comment by kaiwas** [comment]
It's definitely improved. But it's still not as good as it was in version 1.1. https://github.com/FreeCAD/FreeCAD/pull/30412#issuecomment-4554378298
Maybe there's some dependency on the display manager? I'm using X11, but I'll try Wayland now.

UPD/ The situation is similar with Wayland. You can make a choice, but you have to be very careful.
